Add locale map from source Id bean
russdanner/editorial-locale pull request #3
Opened 2021-08-25 09:57 UTC by phuongnq

2021-08-25 10:15 UTC, phuongnq commented
Sample REST script URL: http://localhost:8080/api/plugins/control/custom-locale/locale-map.json?sourceId=794ff24c-039f-a778-84ea-8a97a1908fd0
Sample result:

```
{
    "en": "/site/website/en/articles/2016/12/top-books-for-young-women/index.xml",
    "fr": "/site/website/fr/articles/2021/05/top-books-for-young-women-c7be04cd/index.xml"
}
```

2021-08-25 13:49 UTC, avasquez614 requested changes

2021-08-25 13:49 UTC, avasquez614 commented on scripts/classes/plugins/control/customlocale/LocaleHelper.groovy
> +        if (!sourceId) return result
Please use:

```
if (!sourceId) {
}
```

We by convention don't like `if` one-liners.

2021-08-25 13:49 UTC, avasquez614 commented on scripts/rest/plugins/control/custom-locale/locale-map.get.groovy
> +if (!sourceId) return [:]
Please use:

```
if (!sourceId) {
}
```

We by convention don't like `if` one-liners.

2021-08-26 01:56 UTC, phuongnq commented on scripts/classes/plugins/control/customlocale/LocaleHelper.groovy
> +        if (!sourceId) return result
Updated to use {}

2021-08-26 01:56 UTC, phuongnq commented on scripts/rest/plugins/control/custom-locale/locale-map.get.groovy
> +if (!sourceId) return [:]
Updated to use {}

2021-09-20 10:01 UTC, phuongnq commented
ported to https://github.com/avasquez614/wwwpokemoncom/pull/2

2021-09-20 10:01 UTC, closed without merging